import {makeStyles} from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  circle: ({color}: any) => ({
    width: 22,
    height: 22,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    // background: color
  }),
  wrap: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    width: 48,
    height: 48,
    cursor: 'pointer',
    boxSizing: 'border-box'
  },
  c1: ({color}: any) => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    background: color,
    position: 'absolute',
    opacity: 0.2,
    width: 48,
    height: 48,
    animation: 'pulse1 2.5s linear 0s infinite',
    top: 0,
    left: 0,
  }),
  c2: ({color}: any) => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    background: color,
    position: 'absolute',
    opacity: 0.4,
    width: 36,
    height: 36,
    animation: 'pulse2 2.5s linear 0s infinite',
    top: 6,
    left: 6,
  }),
  c3: ({color}: any) => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '50%',
    background: color,
    position: 'absolute',
    opacity: 0.6,
    width: 24,
    height: 24,
    animation: 'pulse3 2.5s linear 0s infinite',
    top: 12,
    left: 12,
  }),
}));
